### PR TITLE
Disable dark mode for sample apps

### PR DESCRIPTION
**Pull request by bbirman**

### CODE REVIEW

**Comment by bhariharan** [comment]
Why are we disabling dark mode in our sample apps?

**Comment by bbirman** [comment]
We decided not to update the content of the hybrid samples to work with dark mode

**Comment by bhariharan** [comment]
Sure, but we could keep it to the system default for the native screens in the SDK, right?

**Comment by brandonpage** [comment]
I have not done this yet on Android but I think it makes sense.  Leaving it system default would make for an inconsistent experience if the app is not going to support dark mode, right?

**Comment by bbirman** [comment]
Ditto, we can but I thought it looked weird to have a mismatch

**Comment by bhariharan** [comment]
I don't know. I'd rather not force disable it on any of our sample apps or templates. Real users are going to use these samples and they can choose to create/disable if they want to. I'd prefer that we leave it to system default and not force disable even though we don't add assets for dark mode in our hybrid samples.

**Comment by brandonpage** [comment]
For templates, sure.   However, customers aren't using out sample apps as the basis to build their own.  They should use them as examples of best practices, which I think this demonstrates.

**Comment by bhariharan** [comment]
Many customers do take our sample apps and swap out the assets in hybrid and react native. I agree that we should demonstrate best practices. However, I do not agree that forcing a single mode is best practice. Best practice is always respecting the system default, i.e. removing the hardcoded light mode plist value.

**Pull request merged**
